name: Build APK Uji

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil repositori
        uses: actions/checkout@v4

      - name: Siapkan Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Instal dependensi
        run: |
          cd aplikasi_uji
          flutter pub get

      - name: Build APK
        run: |
          cd aplikasi_uji
          flutter build apk --release

      - name: Simpan APK untuk diunduh
        uses: actions/upload-artifact@v4
        with:
          name: APK-Uji-Absensi
          path: aplikasi_uji/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          retention-days: 7
